### PR TITLE
Feature 90545: SSO Authentication (Updated Branch)

### PR DESCRIPTION
**Pull request by desousamario85**
SSO Function has been added to the existing code. 
modified the Home.tsx to have the login screen and then show the feed and leaderboard components.
image

Made the footer conditional. By adding **?hideNavBar=true** this will hide the Footer
With Footer
image

With Out Footer
image

Made sure the footer is on top on the components.

### CODE REVIEW

**Comment by BenGWeeks** [comment]
I don't follow why `Home.tsx` can't be left as-is. I can tell from screenshots that the home screen is no longer correct (wrong background, wrong fonts, additional info, etc. etc.). Moving to draft.

FYI @EdiWeeks

**Comment by BenGWeeks** [comment]
Bug: FooterComponent should not be on the login screen
Assigned to: @desousamario85 

FYI @Ediweeks

**Comment by desousamario85** [comment]
Made changes to the code. new Login.tsx. updated the routing.
image
Authenicated users will be redirected to the Home.tsx page with the URL or /leaderboard.
image

**Comment by BenGWeeks** [comment]
Why not just `<Route path="/Home" element="{<Home/>}"/>`?

**Comment by BenGWeeks** [comment]
> Why not just `<Route path="/Home" element="{<Home/>}"/>`?

Discussed `Home` -> `Feed`.

**Comment by desousamario85** [comment]
renamed the Home.tsx file to match the designs in the bot framework. 
Made the footer hidden for unauthenicated users.
Updated the Login.tsx styling.

**Comment by EdiWeeks** [comment]
[Bug 91603](https://dev.azure.com/EvrosPowerPlatformTeam/Default/_workitems/edit/91603): Details should not be on Home screen
[Bug 91606](https://dev.azure.com/EvrosPowerPlatformTeam/Default/_workitems/edit/91606): Incorrect font in multiple screens
[Bug 91596](https://dev.azure.com/EvrosPowerPlatformTeam/Default/_workitems/edit/91596): FooterComponent should not be on the login screen

**Comment by BenGWeeks** [comment]
I don't think you have latest from main. Missing Total Zaps and other fixes.

**Comment by desousamario85** [comment]
> I don't think you have latest from main. Missing Total Zaps and other fixes.
> 
> Also fixes I previously made to the login screen (such as background fade) are missing.

Everything was from Main,
my SSOv2 Branch
image
Ben's Main branch. The PR was came after I created my new branch.
image

**Comment by BenGWeeks** [comment]
Ok, I think we have merge conflicts as changes to the same files. Can you resolve please?

**Comment by desousamario85** [comment]
The bug and enhancements mentioned are in another PR no. 20  pending merge, checked with Edit.
Making minor adjustments on the login layout.

**Comment by BenGWeeks** [comment]
Looks like still merge conflicts @desousamario85

**Pull request merged**
