### PR TITLE
User Story 90790: As a teammate, I would like to redeem a reward

### PR DESCRIPTION
**Pull request by NataliaMilgevskaya**

### CODE REVIEW

**Comment by NataliaMilgevskaya** [comment]
draft PR

**Comment by EdiWeeks** [comment]
@NataliaMilgevskaya 
Please take a look at these:
[Bug 91604](https://dev.azure.com/EvrosPowerPlatformTeam/Default/_workitems/edit/91604): QR code is blank
[Enhancement 91605](https://dev.azure.com/EvrosPowerPlatformTeam/Default/_workitems/edit/91605): Rephrase Title

**Comment by BenGWeeks** [comment]
Ooh :-) Noice

**Comment by BenGWeeks** [comment]
Thanks, @NataliaMilgevskaya. We looked into creating an Order through the API, and it doesn't look like it's (easily) possible. Our intention is to create an order event through Nostr, which we're not going to have time to implement this Sprint. The ability to purchase was always nice to have anyway! So, we changed the pop-up to be a confirmation, and simply creates an e-mail to the store owner with a request that you would like to purchase a reward and the transaction would be handled offline.

Ref: https://t.me/c/1709198359/936

**Comment by BenGWeeks** [comment]
We also discussed applying a fixed width (see Home page) with a 20px margin and top-aligning the content boxes. The rewards in the carousel should also be individually a fixed width.

**Comment by EdiWeeks** [comment]
[Bug 91656](https://dev.azure.com/EvrosPowerPlatformTeam/Default/_workitems/edit/91656): Pop up should disappear after email was sent

**Comment by EdiWeeks** [comment]
Tested, fixed. This is ready to merge @BenGWeeks

**Comment by BenGWeeks** [comment]
I resolved the merge conflict. Can you quickly check that the rewards functionality works with authenticated login @EdiWeeks

**Pull request merged**
