### PR TITLE
Bug 90992: Wallet is not linked (ensureUserSetup)

### PR DESCRIPTION
**Pull request by desousamario85**
updated teh userService file to ensure all required variables were populated.
Added in the GetUserProfile function to get information from Office 365
Added a displayname sanitize function to ensure there are no special characters in the username

### CODE REVIEW

**Comment by BenGWeeks** [comment]
Nice. Worth checking the automation branch too. Might be some bits in there.

**Comment by BenGWeeks** [comment]
Tested this @EdiWeeks?

**Comment by desousamario85** [comment]
Enhancement 91745 : Ability to sign out (link in the footer)

**Comment by BenGWeeks** [comment]
> Enhancement 91745 : Ability to sign out (link in the footer)

Not sure that really belongs this this PR but OK.

**Comment by BenGWeeks** [comment]
Other than this bug, where it takes the second attempt to know you are setup correctly:
 
image

I think to do with order of `onMessage` and `onCommand` fire or something.
 
Also, note that the code has a flag to run `ensureUserSetup()` only once, then after that it assumes your account is good. I.e. if you delete the account half way through talking to it, you may have issues. Maybe should check every time you send a command, but will be slower.

**Comment by BenGWeeks** [comment]
Not that we now need the `LNBITS_INITIAL_ALLOWANCE` environment variable @akash2017sky / @desousamario85

**Comment by EdiWeeks** [comment]
[Enhancement 91908](https://dev.azure.com/EvrosPowerPlatformTeam/Default/_workitems/edit/91908): No underline on Sign Out on footer on mouseover

**Comment by EdiWeeks** [comment]
Reviewed, users and wallets correctly created, functions are working in the bot. Ready to merge @BenGWeeks

**Pull request merged**
