### PR TITLE
Added filter to remove the logged in user from the choices to send Za…

### PR DESCRIPTION
**Pull request by desousamario85**
Createed global variables in the globalstate.ts in the root directory. defined addobjectDI and UserEmail

image
 added extra steps to filter the list of users to excluded the logged in person.
 
 
image
Now my account is not showing as I was the person running the bot.

image

### CODE REVIEW

**Comment by BenGWeeks** [comment]
I would like to store a `User` object in the state, and then you can do `currentUser.email`, `currentUser.aadObjectId`, etc.

**Comment by desousamario85** [comment]
Updated the globalstate file to get the schema from global.d.ts
image
Add in function to get the current user details 
image
This provides use with more details on the user and provides the email address
update the function to use currentUser.aadobjectId
image

**Comment by BenGWeeks** [comment]
Can you call getUserWallet (or something like that to populate those as well)?

**Comment by desousamario85** [comment]
We can, we need to reimplement the ensureUserWallet function to  make sure every logged in user has a wallet.

**Pull request merged**
